### ISSUE TITLE
Macro Tab not showing up[BUG]

### ISSUE THREAD

**Issue by ravingdragoon** [arcanistzed/sidebar-macros#1]
**Describe the bug**
New tab not appearing in sidebar

**To Reproduce**

Launch foundry with only Sidebar Macros enabled.

**Expected behavior**
A new Macros tab in the sidebar should appear.

**Foundry VTT version:**
Foundry 0.8.9 and Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Additional context**
It also does not work with libWrapper or any other modules enabled. There is no errors or warnings at all in the F12 console.

**Comment by waterlava** [comment]
Do you have any other modules enabled?

**Comment by arcanistzed** [comment]
Do you have any other modules enabled?

**Comment by ravingdragoon** [comment]
I tried with every other module disabled. It doesn't appear for some reason.

**Comment by arcanistzed** [comment]
Do you see any errors in your browser console (F12)?

**Comment by ravingdragoon** [comment]
There are no errors in the console. See video.

https://user-images.githubusercontent.com/72875320/132107011-7fd41522-bd7b-4356-85db-0b2ddc89e8f4.mp4

**Comment by arcanistzed** [comment]
Apparently I had forgotten to make a new release after fixing this a few days ago. :unamused: 

Let me know if it works now on the new version :smile:

**Comment by ravingdragoon** [comment]
Unfortunately, it is still not working for me. Exact same result as the previous video. I do have a (possibly) related warning that I found, not sure if it was there before as I was only looking for errors, see below:

data.mjs:294 MacroData folder "mfolder_rdrnd3acer" is not a valid Folder id  
validate @ data.mjs:294  
DocumentData @ data.mjs:48  
MacroData @ data.mjs:891  
Document @ document.mjs:46  
BaseMacro @ documents.mjs:600  
(anonymous) @ foundry.js:9199  
Macro @ foundry.js:14733  
_initialize @ foundry.js:10161  
WorldCollection @ foundry.js:10147  
Macros @ foundry.js:11230  
initializeEntities @ foundry.js:4421  
setupGame @ foundry.js:4379  
async function (async)  
setupGame @ foundry.js:4375  
_initializeGameView @ foundry.js:5213  
_initializeView @ foundry.js:5189  
initialize @ foundry.js:4286  
async function (async)  
initialize @ foundry.js:4280  
window.addEventListener.once @ foundry.js:53613  
async function (async)  
window.addEventListener.once @ foundry.js:53612

**Comment by arcanistzed** [comment]
I can't reproduce this, but I'm reopening the issue. If anyone else has this issue, let me know. I'll also take another look later.

**Comment by DOMtheDM** [comment]
Wanted to add to this. With other modules enabled I'm not seeing thesidebar tab for macros at all. When I have ONLY Sidebar Macros active I don't see the tab but if I click the macro icon next to the hotbar it disappears and the macros tab appears in the sidebar. BUT when I click on the tab it's empty and I have no access to my macros. No errors in the console at all.
0.8.9
DnD5e (latest update)
AWS Hosted w/ Ubuntu

**Comment by ravingdragoon** [comment]
Quick add to my info.. Hosted on The Forge

**Comment by waterlava** [comment]
Let me know if v0.1.2 doesn't solve this issue

**Comment by arcanistzed** [comment]
Let me know if v0.1.2 doesn't solve this issue

**Comment by ravingdragoon** [comment]
It is solved! Doesn't work with Macro Folders, but it is working as intended :)
