### ISSUE TITLE
[Bug]: Macros Directory Icon doesn't show up on Firefox

### ISSUE THREAD

**Issue by esheyw** [arcanistzed/sidebar-macros#12]
### Expected Behavior

brave: https://i.imgur.com/HBXBzVg.png
chrome: https://i.imgur.com/mNBKFxi.png

### Current Behavior

Firefox: https://i.imgur.com/p01tiiN.png

### Steps to Reproduce

load a world with sidebar macros enabled, make sure neither hide checkbox is checked, notice that you're still not seeing a macro directory icon

### Version

0.8.1

### Foundry VTT Version

9.269

### Operating System

Windows

### Browser / App

Firefox

### Game System

pf2e 3.9.2

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Firefox doesn't seem to support the CSS Typed OM yet... :disappointed: 
https://caniuse.com/mdn-api_css_px
