### ISSUE TITLE
[Bug]: Right-click context menu broken in v10

### ISSUE THREAD

**Issue by Doresain** [arcanistzed/sidebar-macros#16]
### Expected Behavior

Right click on a macro. Get a context menu.

### Current Behavior

Right click on a macro. Don't get a context menu.

### Steps to Reproduce

1. Right click on a macro when on v10.
2. Profit.

### Context

![image](https://user-images.githubusercontent.com/26096062/193768685-2ed4d231-f260-4f8f-8171-148981e36661.png)

Suspect this is because of the ENTITY_PERMISSIONS reference which is no longer available in CONST as of v10.

Didn't PR for this since idk how you want to solve it - release a new ver for v10 or do some version checking and branching within the code.

### Version

0.8.2

### Foundry VTT Version

10

### Operating System

Windows

### Browser / App

Chrome

### Game System

n/a

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
I believe this should fix the issue 5ec2150efc6dd6046ad776380e8af12ffe17af6d
