### ISSUE TITLE
[Bug]: Can't Right-Click on macros in sidebar

### ISSUE THREAD

**Issue by MaxPat931** [arcanistzed/sidebar-macros#17]
### Expected Behavior

Right-click on macro in sidebar to access context menu

### Current Behavior

Right-Click - nothing happens, error in console
![image](https://user-images.githubusercontent.com/86370342/197919794-c76f2050-566c-4903-a072-1bad21d0e653.png)

### Steps to Reproduce

1. Open Macro sidebar
2. Right-click on a Macro
3. Open console, view error

### Context

Updates to lines 197-202

```js
						macro.type === "script" &&
						(macro.permission === CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER||
							macro.testUserPermission(
								game.user,
								CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER ?? CONST.DOCUMENT_PERMISSION_LEVELS.OWNER
							))
```

### Version

0.8.2

### Foundry VTT Version

10.288

### Operating System

Win

### Browser / App

Chrome

### Game System

Dnd5e 2.0.3

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Fixed by 5ec2150efc6dd6046ad776380e8af12ffe17af6d
