### ISSUE TITLE
[FEAT] Support macro folders

### ISSUE THREAD

**Issue by xdy** [arcanistzed/sidebar-macros#2]
**Is your feature request related to a problem? Please describe.**
It would be real useful to have support for the macro folders added by https://github.com/earlSt1/vtt-macro-folders

**Describe the solution you'd like**
I want to be able to see any current macro folders as well as be able to add and remove macro folders from the sidebar.

**Describe alternatives you've considered**
Your own implementation that doesn't interact with macro-folders would also be useful, but it seems a shame to duplicate efforts.

**Additional context**
n/a

**Comment by arcanistzed** [comment]
I'm talking with the dev of Macro Folders about this 👍

**Comment by arcanistzed** [comment]
Macro folders are in v9: https://gitlab.com/foundrynet/foundryvtt/-/issues/5918

**Comment by arcanistzed** [comment]
They will be automatically supported by this module at that point, but I have some code I'll release in the meantime soon.

**Comment by arcanistzed** [comment]
Implemented in [0.2.0](https://github.com/arcanistzed/sidebar-macros/releases/tag/0.2.0) for v9
