### ISSUE TITLE
[Bug]: Using 'Token Action HUD' has an overflow bug when sidebar macro module is 'hiding macro bar'

### ISSUE THREAD

**Issue by nirurin** [arcanistzed/sidebar-macros#23]
### Expected Behavior

Hiding the macro bar should have no other knock-on effects. 

### Current Behavior

Hiding the macro bar causes the 'token action hud' to think the screen is a lot smaller than it is, causing it to think it needs to overflow (resulting in a scroll bar, instead of the list of spells etc filling the screen). 

https://github.com/Drental/fvtt-tokenactionhud/issues/327

A link to the issue on their side. 

### Steps to Reproduce

See above.

### Version

Current

### Foundry VTT Version

10

### Operating System

windows 11

### Browser / App

Microsoft Edge

### Game System

dnd5e

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
I'm not doing anything other than removing the element and it would be Token HUD's responsibility to adjust its height to fit its contents regardless of whether the hotbar is present.
