### ISSUE TITLE
[FEAT] DnD5e UI compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [arcanistzed/sidebar-macros#5]
**Describe the bug**
The module is not playing nicely with DnD5e UI

**To Reproduce**
Steps to reproduce the behavior: Install and activate DnD5e UI

Look at the right hand toolbar. The Chat tab is pushed off the bar to the left because the Sidebar Macros tab is not reading the style.

**Expected behavior**
The Sidebar Macros tab should allow itself to have the style changed to be compatible with non-core themes.

**Screenshots**
![image](https://user-images.githubusercontent.com/72875320/147574092-e3b5f9ed-463b-4990-a66d-34efab822373.png)

**Details**
Foundry VTT version: V9 Stable 1
Module version: Sidebar Macros v0.4.0	DnD5e UI v9.238.2

**Comment by ravingdragoon** [comment]
I submitted this as an issue to the DnD5e UI module and the dev said that they cannot fix it from their side.

**Comment by arcanistzed** [comment]
I took a look and I think that it needs to be resolved on their side. They include icons for all of the sidebar tabs, but not for macros.
I'll DM them and get back to you.

**Comment by arcanistzed** [comment]
Ok, they will be fixing this on their end

**Comment by arcanistzed** [comment]
![](https://puu.sh/IA7TR/d758c48796.png)
